### ISSUE TITLE
Low risk (LR-1): ` modifier onlyKeeper()` can have keepers and as well `address(0)` allowing anyone to call keepers methods

### ISSUE THREAD

**Issue by petrovska-petro** [BalancerMaxis/ChildGaugeInjectorV2#10]
**Severity:** low risk. Constrained into `performUpkeep` impact

**Context:** `setKeeperAddresses` will allow setting an array of addresses, and in the case of one of them being `address(0)` by an operational mistake by the integrator or intentional, it will allow anyone to call keeper methods, which may not be desired, reference:

```
 if (msg.sender == KeeperAddresses[i] || KeeperAddresses[i] == address(0)) {
    isKeeper = true;
    break;
 }
```

**Recommendation:** Have a clear differentiation if the intention is to give a wide keeper access to any EOA or not in at the `setter` level.

Generally, having `address(0)` as wildcard in exchange of flexibility can have unknown repercusions at the operational level if the `setter` it is nor properly construct.

If this differentation is introduced and that behaviour is wished to be managed, it is advisable to included tests with different types of `newKeeperAddress`. e.g: [address(0), address(135)], [address(0)], [address(12343), address(13335434)]

## Review stage 

Balancer Maxis:
- [x]  Acknowledge
- [ ]  Fixed

Onchainification Labs:
- [x]  Acknowledge correction/mitigation

**Comment by Tritium-VLK** [comment]
This was by intention.  In many cases we would like anyone to keep.  It is based on the assumption that the only thing the keeper can do is schedule a due injection if there are sufficient tokens to cover it.

**Comment by Tritium-VLK** [comment]
@petrovska-petro note that this is already mentioned in the heredoc for the param.  Will add a comment too in a PR>

**Comment by petrovska-petro** [comment]
@Tritium-VLK to clarify on the issue, we're aware it's intentional, but our point being, which we believe it's not handle at the `setter` level is the following:

```
case A): [address(0)] --> expected behaviour anyone could keep

case B): [address(4343), address(434343), address(0)] --> can lead to unexpected behaviour 
```

case A) ✅ 

case B) it's intentional that `address(4343)` and `address(434343)` will be able to keep, but by any chance an operational mistake is executed and in the array `address(0)` is included, and will create from my pov and unexpected behaviour where basically anyone could keep, instead of only: `address(4343)` and `address(434343)`, which could be the expected

the suggestion was that on a misconfiguration on the setter that case being handle gracefully (if considered undesired)

let me know if this clarifies deeper our comments around the modifier and if it is something that it's indeed to be allow by design and not concerning for potential integrators on unexpected behaviour

**Comment by Tritium-VLK** [comment]
The heredocs clearly state that a 0 anywhere in the list is a wildcard and that yes then anyone can keep, hence expected behavior.

We thought about making the performUpkeep permissionless.  The keeper isn't really able to do anything but pay gas to execute something due.  In the end I think we wanted to maintain the ability to not always have an open list and instead have more control.

Your suggestion would be to only allow a 0x0 member in this list if is the only member, and to throw a revert of some sort on the setter if 0x0 was included in a list with more than len 1.

As this is a PoC I'm trying to make minimal changes/not add more logic while we figure out who/how to build whatever comes next.  Let me ping @Zen-Maxi who will be the primary operator of this injector and see what he thinks.  If he agrees it is confusing and there is some risk as it stands, can add some more lines of code to handle this.

**Comment by Tritium-VLK** [comment]
@Zen-Maxi any thoughts on the discussion above?

**Comment by Tritium-VLK** [comment]
Spoke about this in a meeting.  Zen/users agree it is fine.  We can explain in the UI and when showing this to users/in docs.

**Comment by petrovska-petro** [comment]
Overall feedback indicates that team internally agrees on current setup and that further explanation/details will be work into the ui/docs to document these intricacies.

We're marking this issue as "Acknowledge correction/mitigation" and closing it.
